# Generated by Django 5.1.6 on 2025-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catList', '0009_alter_cat_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed_en',
            field=models.CharField(default='British Shorthair', max_length=100, verbose_name='Breed (EN)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed_es',
            field=models.CharField(default='British Shorthair', max_length=100, verbose_name='Raza (ES)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description_en',
            field=models.TextField(default='Friendly Cat', verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description_es',
            field=models.TextField(default='Gato Amable', verbose_name='Descripción (ES)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name_en',
            field=models.CharField(blank=True, default='Joe', max_length=100, null=True, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name_es',
            field=models.CharField(default='Juan', max_length=100, verbose_name='Nombre (ES)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='personality_traits_en',
            field=models.CharField(default='Friendly', max_length=100, verbose_name='Personality Traits (EN)'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='personality_traits_es',
            field=models.CharField(default='Cariñoso', max_length=100, verbose_name='Rasgos de personalidad (ES)'),
        ),
    ]
