[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
preDeployCommand = "python3 manage.py migrate && python3 manage.py collectstatic --noinput"
startCommand = "gunicorn catSite.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
